/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout/index'
import { Route as AdminLayoutResumeRouteImport } from './routes/admin/_layout/resume'
import { Route as AdminLayoutProjectsRouteImport } from './routes/admin/_layout/projects'
import { Route as AdminLayoutContentRouteImport } from './routes/admin/_layout/content'

const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutResumeRoute = AdminLayoutResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutProjectsRoute = AdminLayoutProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutContentRoute = AdminLayoutContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/content': typeof AdminLayoutContentRoute
  '/admin/projects': typeof AdminLayoutProjectsRoute
  '/admin/resume': typeof AdminLayoutResumeRoute
  '/admin/': typeof AdminLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/content': typeof AdminLayoutContentRoute
  '/admin/projects': typeof AdminLayoutProjectsRoute
  '/admin/resume': typeof AdminLayoutResumeRoute
  '/admin': typeof AdminLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/_layout/content': typeof AdminLayoutContentRoute
  '/admin/_layout/projects': typeof AdminLayoutProjectsRoute
  '/admin/_layout/resume': typeof AdminLayoutResumeRoute
  '/admin/_layout/': typeof AdminLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/resume'
    | '/admin'
    | '/admin/login'
    | '/admin/content'
    | '/admin/projects'
    | '/admin/resume'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/resume'
    | '/admin/login'
    | '/admin/content'
    | '/admin/projects'
    | '/admin/resume'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/resume'
    | '/admin/_layout'
    | '/admin/login'
    | '/admin/_layout/content'
    | '/admin/_layout/projects'
    | '/admin/_layout/resume'
    | '/admin/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRoute: typeof ProjectsRoute
  ResumeRoute: typeof ResumeRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/resume': {
      id: '/admin/_layout/resume'
      path: '/resume'
      fullPath: '/admin/resume'
      preLoaderRoute: typeof AdminLayoutResumeRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/projects': {
      id: '/admin/_layout/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminLayoutProjectsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/content': {
      id: '/admin/_layout/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminLayoutContentRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface AdminLayoutRouteChildren {
  AdminLayoutContentRoute: typeof AdminLayoutContentRoute
  AdminLayoutProjectsRoute: typeof AdminLayoutProjectsRoute
  AdminLayoutResumeRoute: typeof AdminLayoutResumeRoute
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutContentRoute: AdminLayoutContentRoute,
  AdminLayoutProjectsRoute: AdminLayoutProjectsRoute,
  AdminLayoutResumeRoute: AdminLayoutResumeRoute,
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRoute: ProjectsRoute,
  ResumeRoute: ResumeRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
